### PR TITLE
make compatibility changes

### PR DESCRIPTION
**Pull request by sladyn98**

### CODE REVIEW

**Comment by sladyn98** [comment]
@nealef Kindly review

**Comment by nealef** [comment]
As keys is a parameter defined as unsigned char *, I would cast the parameter in the DES_set_key() call to (const DES_cblock *) - note it's almost the same as OpenSSL version except there's a space between const and DES_cblock. For example,

```
DES_set_key((const DES_cblock *) keys, &key_schedule1);
```

**Comment by sladyn98** [comment]
Kindly review .

**Comment by nealef** [comment]
Prefer space between parameters:
```
DES_set_key((const DES_cblock *) keys,&key_schedule1); -> DES_set_key((const DES_cblock *) keys, &key_schedule1);
```

**Comment by sladyn98** [comment]
Done :+1: Kindly give an approval on this officially via the review option so I can merge :)

**Comment by nealef** [comment]
+1

**Comment by sladyn98** [comment]
I have an idea let's finish all of the compatibility issues and then merge that would make it easier to review

**Comment by nealef** [comment]
Yep.

**Review by nealef — APPROVED** [review]

**Review by nealef — APPROVED** [review]

**Review by nealef — APPROVED** [review]

**Pull request merged**
