### PR TITLE
Removed `- lcrypto`

### PR DESCRIPTION
**Pull request by sladyn98**
Removed `-lcrypto` to run the makefile

### CODE REVIEW

**Comment by sladyn98** [comment]
@nealef Kindly have a look.

**Review by nealef — APPROVED** [review]
You can probably use the .gitignore file to ignore the .po files that are being generated (you’ll also have to git rm them to get them out of the repo). Makefile should not be under git control either as it is generated by the boostrap script.

**Comment by sladyn98** [comment]
Yeah we could decide to not have this merged.

**Comment by sladyn98** [comment]
All commits with respect to makefile and configure will be run locally and if required be pushed to this PR.Till then it will remain closed.

**Pull request closed without merging**
