### PR TITLE
Warning Reductions during linkage of libica and boringSSL

### PR DESCRIPTION
**Pull request by sladyn98**
Reducing the warnings in linking of libraries.

### CODE REVIEW

**Comment by sladyn98** [comment]
@nealef Kindly have a look

**Review by nealef — APPROVED** [review]

**Comment by sladyn98** [comment]
@nealef With respect to https://github.com/google/boringssl/blob/d6f9c359d219055a89c676cb8886421b145a08da/include/openssl/bn.h#L640. BoringSSL seems to have used only a single method while setting the struct and moreover the `set_old` method seems to be a callback with null arguments.But in case we come across any further complications we can add the definition if required.

References:
https://commondatastorage.googleapis.com/chromium-boringssl-docs/bn.h.html
https://github.com/google/boringssl/blob/master/include/openssl/bn.h#L640

**Review by nealef — APPROVED** [review]

**Review by nealef — APPROVED** [review]

**Review by nealef — APPROVED** [review]

**Comment by sladyn98** [comment]
@rultor hello

**Comment by sladyn98** [comment]
Our work with this PR is done for now .
@nealf We will revisit this when needed.

> Those links are creating applications to they will need to also link against BTLS. So you need to include the btls static library. As we haven’t built this yet then the target we build first is just the static library. I assume there’s a make target for it. When you’ve built btls we can revisit and build the apps (icainfo, icastats)

**Pull request merged**
